apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: p808ez5we-python 
  janus-idp.io/tekton: p808ez5we-python
  backstage.io/kubernetes-id: p808ez5we-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p808ez5we-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml