apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: p808ez5we-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: p808ez5we-python 
  name: p808ez5we-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: p808ez5we-python 
